routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController ;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController ;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'home'])->name('home');

Route::get('/home/{firstname}/{lastname}', function ($firstname, $lastname){

    return view('home', compact('firstname', 'lastname')) ;
});

Route::resource('categories', CategoryController::class) ;

Auth::routes();

Route::get("logout", [HomeController::class, 'logout']) ;

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::group(['middleware' => ['auth']],
    function(){
    Route::resource('roles', RoleController::class) ;
    Route::resource('users', UserController::class) ;
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $users = User::orderBy('id','desc')->paginate(5) ;

        return view('users.index', compact('users'))
            ->with('i', ($request->input('page', 1)-1) * 5);

    }

    public function create() {

        $roles = Role::pluck('name', 'name')->all() ;

        return view('users.create', compact('roles')) ;
    }

    public function store(Request $request)
    {
        $this->validate($request, [
           'name' => 'required',
           'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password',
            'roles' => 'required'
        ]);

        $input = $request->all() ;
        $input['password'] = Hash::make($input['password']) ;

        $user = User::create($input) ;
        $user->assignRole($request->input('roles')) ;

        return redirect()->route('users.index')
            ->with('success', 'Utilisateur enregistré avec succès !');
    }

    public function show($id){

        $user = User::find($id) ;

        return view('users.show', compact('user')) ;
    }
}

resources/views/users/create.blade.php
@extends('layouts.layout')

@section("title") Enregister un nouvel utilisateur @endsection

@section('body')
    <div class="container m-5">
        <div class="row">
            <div class="col-12">
                {!! Form::open(array('route' => 'users.store', 'method' => 'POST')) !!}
                    <div class="col-12">
                        <div class="form-group">
                            <strong>Nom complet</strong>
                            {!! Form::text('name', null,
                            array('placeholder' => 'Nom de l\'utilisateur', 'class' =>'form-control')) !!}
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <strong>Email</strong>
                            {!! Form::email('email', null,
                            array('placeholder' => 'Email', 'class' =>'form-control')) !!}
                        </div>
                    </div>
                <div class="col-12">
                        <div class="form-group">
                            <strong>Mot de passe</strong><br>
                            {!! Form::password('password', null,
                            array('placeholder' => 'Mot de passe', 'class' =>'form-control')) !!}
                        </div>
                </div>
                <div class="col-12">
                        <div class="form-group">
                            <strong>Confirmation du mot de passe</strong><br>
                            {!! Form::password('confirm-password', null,
                            array('placeholder' => 'répéter le mot de passe', 'class' =>'form-control')) !!}
                        </div>
                </div>
                <div class="col-12">
                        <div class="form-group">
                            <strong>Rôles</strong><br>
                            {!! Form::select('roles[]', $roles, [],
                            array('class' => 'form-control', 'multiple')) !!}
                        </div>
                    </div>
                <div class="col-12">
                        <button type="submit" class="btn btn-block btn-primary">
                            Enregistrer
                        </button>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.layout')

@section('title') Utilisateurs @endsection

@section('body')

    <div class="container m-4">
        <div class="row">
            <div class="col-12">
                <div class="pull-left">
                    <h2>Gestion des utilisateurs</h2>
                </div>
                <div class="pull-right">
                    <a href="{{ route('users.create') }}" class="btn btn-primary">
                        Enregistrer un nouvel utilisateur
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">

                @if($message = Session::get('success'))
                    <p>{{ $message }}</p>
                @endif

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>N°</th>
                        <th>Nom complet</th>
                        <th>Email</th>
                        <th>Rôles</th>
                        <th width="280px">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>
                                @if(intval(count($user->getRoleNames())) != 0)
                                    @foreach($user->getRoleNames() as $role)
                                        <label class="badge badge-success">
                                            {{ $role }}
                                        </label>
                                    @endforeach
                                @else

                                    <label class="badge badge-secondary">
                                        Pas de rôle
                                    </label>
                                @endif
                            </td>
                            <td>
                                <a class="btn btn-info" href="{{ route('users.show', $user->id) }}">
                                    <span class="fa fa-eye"></span>
                                </a>
                                <a class="btn btn-info" href="{{ route('users.edit', $user->id) }}">
                                    <span class="fa fa-edit"></span>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>

                    <tfoot>
                        {!! $users->render() !!}
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

@endsection

resources/views/users/show.blade.php
@extends('layouts.layout')

@section("title") {{ $user->name }} @endsection

@section('body')
    <div class="container m-5">
        <div class="row">
            <div class="col-12">
                <div class="pull-left">
                    <h2>Affichage d'un utilisateur</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <strong>Nom complet :</strong>
                    {{ $user->name }}
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <strong>Email :</strong>
                    {{ $user->email }}
                </div>
            </div>


            <div class="col-12">
                <div class="form-group">
                    <strong>Roles :</strong>
                    @if(!empty($user->getRoleNames()))
                        @foreach($user->getRoleNames() as $role)
                            <label class="badge badge-success">
                                {{ $role }}
                            </label>
                        @endforeach
                    @endif
                </div>
            </div>

        </div>
    </div>
@endsection