routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController ;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController ;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'home'])->name('home');

Route::get('/home/{firstname}/{lastname}', function ($firstname, $lastname){

    return view('home', compact('firstname', 'lastname')) ;
});

Route::resource('categories', CategoryController::class) ;

Auth::routes();

Route::get("logout", [HomeController::class, 'logout']) ;

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::group(['middleware' => ['auth']],
    function(){
    Route::resource('roles', RoleController::class) ;
    Route::resource('users', UserController::class) ;
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name'] ;


    //récupération de tous les produits d'une catégorie
    public function products(){
        return $this->hasMany(Product::class) ;
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all() ;

        return view('categories/index', compact('categories')) ;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories/create') ;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all() ;

        Category::create($data) ;

        return redirect()->route('categories.index') ;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('categories/show', compact('category')) ;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categories/edit', compact('category')) ;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //$data = $request->all() ;

        //First
        $category->name = $request->get('name') ;
        $category->save() ;

        //Second


        return back() ;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete() ;

        return back()->with('success', 'Catégorie supprimé avec succès !') ;
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')

    <h3>Formulaire d'ajout d'une nouvelle catégorie</h3>

    <form action="{{ route('categories.store') }}" method="post">
        @csrf

        @include('categories.form')

    </form>

@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3>Modification de la catégorie "{{ $category->name }}"</h3>

    <form action="{{ route('categories.update',$category->id) }}" method="post">
        @csrf
        @method('PUT')
        @include('categories.form')
    </form>
@endsection

resources/views/categories/form.blade.php
<fieldset>
    <label for="name">Nom de la catégorie</label>
    <input type="text" name="name" id="name" value="{{ $category->name ?? "" }}">
    <br>
    <input type="submit" value="Enregister">
</fieldset>

resources/views/categories/index.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body
    <h1>La liste de toutes mes catégories</h1>

    @if($message = Session::get('success'))
        <p>{{ $message }}</p>
    @endif

    <table border="1">
        <thead>
            <th>Nom</th>
            <th>Actions</th>
        </thead>
        <tbody>
        @foreach($categories as $category)
            <tr>
                <td>{{ $category->name }}</td>
                <td>
                    <a href="{{ route('categories.show', $category->id) }}">
                        Afficher
                    </a>
                    <a href="{{ route('categories.edit', $category->id) }}">
                        Modifier
                    </a>
                    <form action="{{ route('categories.destroy',$category->id) }}" method="post">
                        @method('DELETE')
                        @csrf
                        <input type="submit" value="Supprimer">
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <br>

    <a href="{{ route("categories.create") }}">Ajouter une nouvelle catégorie</a>
</body>
</html>

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
    <table>
        <tbody>
            <tr>
                <td>Id : {{ $category->id }}</td>
            </tr>

            <tr>
                <td>Nom : {{ $category->name }}</td>
            </tr>
        </tbody>

        <tfoot>
            <tr>
                <td>
                    <a href="{{ URL::previous() }}">
                        Retour à la liste liste des catégories
                    </a>
                </td>
            </tr>
        </tfoot>
    </table>


@endsection